// Configuración de Supabase
// IMPORTANTE: Reemplaza estas credenciales con las de tu proyecto Supabase

const SUPABASE_URL = 'https://elnmiwhsmppxakbeoegx.supabase.co'; // Reemplaza con tu URL de Supabase
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsbm1pd2hzbXBweGFrYmVvZWd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUzNjIyMzUsImV4cCI6MjA4MDkzODIzNX0.7WJJGXnIEcTUMqAsJuoKwGpCFRNIRZvEcLLlX8cVdBY'; // Reemplaza con tu clave anónima pública

// Inicializar cliente Supabase
const supabase = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

// Nota: Asegúrate de crear la tabla 'specimens' en Supabase con la siguiente estructura:
/*
CREATE TABLE specimens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  family TEXT NOT NULL,
  specimen_name TEXT,
  collection_date DATE,
  depth INTEGER,
  location TEXT,
  notes TEXT,
  identification_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  answers JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
*/